#!/bin/sh
#
# pppd            start pppd
#

start() {
    printf "Starting 3g: "
    /usr/sbin/pppd call td-dailer
    /bin/echo "OK"
}
stop() {
    printf "Stopping 3g: "
    if [ -f "/run/ppp0.pid" ]
    then
        /bin/kill `cat /run/ppp0.pid`
    fi
    /bin/echo "OK"
}
restart() {
    stop
    start
}
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
